DRINKS = [
    {"name": "Mojito", "ingredients": ["white rum", "lime juice", "mint leaves", "simple syrup", "club soda"]},
    {"name": "Whiskey Sour", "ingredients": ["bourbon", "lemon juice", "simple syrup", "cherry"]},
    {"name": "Cosmopolitan", "ingredients": ["vodka", "triple sec", "lime juice", "cranberry juice"]},
    {"name": "Margarita", "ingredients": ["tequila", "lime juice", "triple sec", "salt"]},
    {"name": "Vodka Soda", "ingredients": ["vodka", "club soda"]},
    {"name": "Gin and Tonic", "ingredients": ["gin", "tonic water"]},
    {"name": "Espresso Martini", "ingredients": ["vodka", "coffee liqueur", "simple syrup", "espresso"]},
    {"name": "Batanga", "ingredients": ["blanco tequila", "lime juice", "cola"]},
    {"name": "Sazerac", "ingredients": ["simple syrup", "rye whiskey", "peychaud bitters", "angostura bitters", "absinthe"]},
    {"name": "Long Island Iced Tea", "ingredients": ["vodka", "gin", "white rum", "blanco tequila", "cointreau", "lemon juice", "simple syrup", "cola"]},
    {"name": "Black Russian", "ingredients": ["vodka", "coffee liqueur"]},
    {"name": "Mai Tai", "ingredients": ["dark rum", "lime juice", "orange curacao", "orgeat syrup", "rock candy syrup"]},
    {"name": "Hurricane", "ingredients": ["dark rum", "passion fruit syrup", "lime juice", "maraschino cherry", "orange juice"]},
    {"name": "Amaretto Sour", "ingredients": ["amaretto", "simple syrup", "lemon juice", "orange juice", "maraschino cherry"]},
    {"name": "Dirty Martini", "ingredients": ["gin", "dry vermouth", "olive juice"]},
    {"name": "Vodka Gimlet", "ingredients": ["vodka", "lime juice", "simple syrup"]},
    {"name": "Honey Bee", "ingredients": ["honey", "white rum", "lemon juice"]},
    {"name": "Rosita", "ingredients": ["reposado tequila", "sweet vermouth", "dry vermouth", "campari", "angostura bitters"]},
    {"name": "Champagne Cocktail (Classic)", "ingredients": ["champagne", "simple syrup", "angostura bitters", "lemon"]},
    {"name": "Painkiller", "ingredients": ["dark rum", "pineapple juice", "orange juice", "coconut cream"]},
    {"name": "Cape Codder", "ingredients": ["vodka", "cranberry juice", "lime juice", "club soda"]},
    {"name": "Gold Rush", "ingredients": ["bourbon", "lemon juice", "honey"]},
    {"name": "Gin Rickey", "ingredients": ["gin", "lime juice", "club soda"]},
    {"name": "Tequila Sunrise", "ingredients": ["tequila", "orange juice", "grenadine"]},
    {"name": "Hot Buttered Rum", "ingredients": ["dark rum", "simple syrup", "butter"]},
    {"name": "Vesper", "ingredients": ["dry gin", "vodka", "lillet blanc"]},
    {"name": "Rose Cocktail", "ingredients": ["dry vermouth", "kirschwasser", "raspberry syrup"]},
    {"name": "Brain Duster", "ingredients": ["rye whiskey", "absinthe", "sweet vermouth", "angostura bitters"]},
    {"name": "Paloma", "ingredients": ["reposado tequila", "lime juice", "salt", "grapefruit soda"]},
    {"name": "Greyhound", "ingredients": ["vodka", "grapefruit juice"]},
    {"name": "Screwdriver", "ingredients": ["vodka", "orange juice"]},
    {"name": "Bushwacker", "ingredients": ["dark rum", "coffee liqueur", "chocolate cream liqueur", "cream of coconut", "milk", "whipped cream"]},
    {"name": "Dark and Stormy", "ingredients": ["dark rum", "ginger beer", "lime juice"]},
    {"name": "French 75", "ingredients": ["dry gin", "simple syrup", "lemon juice", "champagne"]},
    {"name": "Boulevardier", "ingredients": ["bourbon", "campari", "sweet vermouth"]},
    {"name": "Gimlet", "ingredients": ["london dry gin", "rose's lime juice"]},
    {"name": "Moscow Mule", "ingredients": ["vodka", "ginger beer", "lime juice"]},
    {"name": "Aperol Spritz", "ingredients": ["aperol", "prosecco", "club soda", "orange juice"]},
    {"name": "Manhattan", "ingredients": ["rye whiskey", "vermouth", "angostura bitters"]},
    {"name": "Dry Martini", "ingredients": ["dry vermouth", "gin"]},
    {"name": "Daiquiri", "ingredients": ["white rum", "simple syrup", "lime juice"]},
    {"name": "Negroni", "ingredients": ["london dry gin", "campari", "vermouth rosso"]},
    {"name": "Old Fashioned", "ingredients": ["bourbon", "angostura bitters", "simple syrup"]},
    {"name": "Irish Coffee", "ingredients": ["coffee", "irish whiskey", "simple syrup", "heavy cream"]},
    {"name": "Mint Julep", "ingredients": ["bourbon", "mint", "simple syrup"]},
    {"name": "Brown Derby", "ingredients": ["bourbon", "grapefruit juice", "honey"]},
    {"name": "Aviation", "ingredients": ["gin", "maraschino liqueur", "creme de violette", "lemon juice"]},
    {"name": "Clover Club", "ingredients": ["lemon juice", "gin", "raspberry syrup", "egg white"]},
    {"name": "Jungle Bird", "ingredients": ["dark rum", "campari", "pineapple juice", "lime juice", "simple syrup"]},
    {"name": "Pickleback", "ingredients": ["irish whiskey", "pickle juice"]},
    {"name": "Sidecar", "ingredients": ["cognac", "cointreau", "lemon juice"]},
    {"name": "French Connection", "ingredients": ["cognac", "amaretto"]},
    {"name": "Between the Sheets", "ingredients": ["cognac", "white rum", "triple sec", "lemon juice"]},
    {"name": "Stinger", "ingredients": ["cognac", "white creme de menthe"]},
    {"name": "Champagne Cocktail (Cognac)", "ingredients": ["simple syrup", "angostura bitters", "cognac", "champagne"]},
    {"name": "Sazerac (Cognac)", "ingredients": ["cognac", "absinthe", "peychaud bitters", "simple syrup"]},
    {"name": "Gold Fashioned", "ingredients": ["bourbon", "honey", "orange bitters"]},
    {"name": "Gin Sour", "ingredients": ["gin", "lemon juice", "simple syrup"]},
    {"name": "Rum Ricky", "ingredients": ["white rum", "lime juice", "club soda"]},
    {"name": "Tequila Collins", "ingredients": ["tequila", "lemon juice", "simple syrup", "club soda"]},
    {"name": "Coffee Sour", "ingredients": ["coffee liqueur", "lemon juice", "simple syrup", "egg white"]},
    {"name": "Orange Blossom", "ingredients": ["gin", "orange juice", "simple syrup"]},
    {"name": "Vodka Collins", "ingredients": ["vodka", "lemon juice", "simple syrup", "club soda"]},
    {"name": "Honey Vodka Lemonade", "ingredients": ["vodka", "lemon juice", "honey", "club soda"]},
    {"name": "Bourbon Buck", "ingredients": ["bourbon", "ginger beer", "lime juice"]},
    {"name": "Cognac Highball", "ingredients": ["cognac", "club soda"]},
    {"name": "Raspberry Vodka Soda", "ingredients": ["vodka", "raspberry syrup", "club soda", "lime juice"]},
    {"name": "Rum Orange Fizz", "ingredients": ["white rum", "orange juice", "simple syrup", "club soda"]},
    {"name": "Cognac Sour", "ingredients": ["cognac", "lemon juice", "simple syrup"]},
    {"name": "Gin Fizz", "ingredients": ["gin", "lemon juice", "simple syrup", "egg white"]},
    {"name": "Vodka Sunrise", "ingredients": ["vodka", "orange juice", "grenadine", "cherry"]},
    {"name": "Jamaican Mule", "ingredients": ["jamaican rum", "ginger beer", "lime juice"]},
    {"name": "Ginger Cognac Smash", "ingredients": ["cognac", "simple syrup", "lemon juice", "ginger beer"]}
]